### PR TITLE
Minor readme updates

### PR DESCRIPTION
**Pull request by lucasjfriesen**
Added minor notes for novices who are unaware of what KIAUH sets up and how macro commands are sent to the printer.

### CODE REVIEW

**Comment by bassamanator** [comment]
Thanks for this, but I'm not seeing how this is adding clarity, or simplifying things for the user, or reducing verbosity.

```
The following steps are completed in the Mainsail web interface. You can locate this at the same ip address as your pi. The KIAUH automatically sets up the services required to run Mainsail when the pi is turned on.
```
Not exactly correct: this step can be completed anywhere. Perhaps the user is going to edit this in their ftp program directly, I myself do edits like this in the terminal, etc.

```
*NB* If you are using KIAUH, in the menu under [4] Advanced, you will find an option to identify the `mcu` port.
```
In order to get the `mcu` path via `kiauh`, the user has to switch to the `kiauh` directory, start `kiauh`, navigate to a menu that is 3 layers deep, all the while having to read the options being displayed. I gave this a try, and as an advanced computer user, and as someone who's been using linux for 15 years, the cognitive load and complexity of the `kiauh` route was easily 20 times greater than simply copy pasting `ls /dev/...`. How is this helping the user?

```
[At this point, it's not possible to tell with certainty whether your flash was successful, continue on with the guide.] A good sign that it worked is the touchscreen not progressing past the Sovol logo on power-on.
```
I suppose this might be helpful, but the user still has to continue onward regardless. Moreover, I, unfortunately, interact with users who are unwilling to read 13 minutes worth of text, and would rather watch a 30+ minute video, pausing and resuming, turning a very short process of installing Klipper, into a more than an hour-long process (sometimes many days worth of troubleshooting actually because they were unwilling to spend 13 doing some reading).

Don't take my post the wrong way, I simply owed you an explanation. Appreciate people like you who like to contribute to open-source projects. I've also adjusted the contribution guide.

PS My stats from work on this repo over this past weekend:
```sh
$ git diff --shortstat master..42bab87f6b7cd2925c3cc2b09118e8e818280372
# 9 files changed, 192 insertions(+), 328 deletions(-)
# removed ~136 lines from the README (328 - 192) 😁
```

**Comment by lucasjfriesen** [comment]
Fair enough, different strokes. You've got a lot more experience in this
than I do. These were just the things that would have saved me ~20 minutes
each during my first setup as I was going through your guide. I suppose I'm
one of the ones who prefers the wall of text to some out of date video.

Cheers, thanks for setting this up.

Also, I've converted Ellis' SuperSlicer profiles for Orca on the SV06 plus.
Once it's polished, is that something you want to provide?

**Comment by bassamanator** [comment]
I prefer the text as well, but balance is key.

OS bundle would be cool.

Can you please:
- Stay in line with Ellis' settings as much as the OrcaSlicer settings _allow_.
- Filename: OrcaSlicer_config_bundle-SV06-Both.(json?)
- Export config bundle with physical printers
- Dimensions (so that I can keep them inline with other bundles):
	- Plus:
		- 300x300x340
	- non-Plus dimensions
		- 223x223x255
- Create a repo holding this bundle so that I can point to it under `Sources`. Alternatively, I can also simply point your github profile, if you prefer.

Just so that you know what you're getting into, this is mostly thankless work, most of my users don't even star the repo. And don't stress about it if you change your mind.

Thanks!

**Comment by lucasjfriesen** [comment]
Sounds good, I'll let you know if/when it's up.

I'm familiar with thankless work :D I'm a statistician by trade.

**Comment by TopoDiFogna** [comment]
I would love an OrcaSlicer Profile!

Trying it myself but something still off with settings. I'm a newbie on setting slicers so i would really be grateful for a profile written by someone who knows what to do :)

**Pull request closed without merging**
